[package]
name = "remote"
version = "1.0.0"
authors = ["giacomogallina", "bortoz"]
edition = "2018"

[dependencies]
clap = "2.32.0"
crossterm = "0.11.1"
rand = "0.7.2"
core = { path = "./remote-core" }
worker = { path = "./remote-worker" }
