[package]
name = "core"
version = "1.0.0"
authors = ["bortoz"]
edition = "2018"

[dependencies]
cookie = "0.12.0"
ssh2 = "0.4.0"
tempfile = "3.1.0"
cookies-loader = { path = "../remote-cookies-loader" }
error = { path = "../remote-error" }
liker = { path = "../remote-liker" }
