[package]
name = "cookies-loader"
version = "1.0.0"
authors = ["bortoz"]
edition = "2018"

[dependencies]
cookie = "0.12.0"
rust-crypto = "0.2.36"
sqlite = "0.25.0"
error = { path = "../remote-error" }
